# Custom Language File for Launcher Customizer

[ejs.app]
title = "liberoPixelmon"

[ejs.landing]
mediaGitHubURL = "https://github.com/Kyujin0526/Libero"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/mUQNJRhzc5"

[ejs.settings]
sourceGithubLink = "https://github.com/Kyujin0526/Libero"
supportLink = "https://github.com/Kyujin0526/Libero/issues"

[ejs.welcome]
welcomeHeader = "리베로 서버팩 모드팩입니다"
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
